server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=home_service
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    io:
      micrometer:
        core:
          instrument: DEBUG