server:
  port: 8080
app:
  email-verification-base-url: http://localhost:8080/api/v1/auth/verify-email
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=home_service
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 441334336d841b
    password: 81601310d36885
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    io:
      micrometer:
        core:
          instrument: DEBUG